export const FETCH_BLOGGER_POSTS = 'FETCH_BLOGGER_POSTS'
export const INSERT_BLOGGER_POST_SUCCESS = 'INSERT_BLOGGER_POST_SUCCESS'
export const INSERT_BLOGGER_POST_FAILURE = 'INSERT_BLOGGER_POST_FAILURE'